version: "3"

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  rebrow:
    container_name: rebrow
    image: marian/rebrow
    ports:
      - 5001:5001
    depends_on:
      - redis
